webhook:
    path: /webhook/telegram
    controller: App\Controller\WebhookController::index
    methods: POST

index:
    path: /
    controller: App\Controller\MainController::index
    methods: GET

app_login:
    path: /login
    controller: App\Controller\LoginController::login
    methods: GET|POST

app_logout:
    path: /logout
    controller: App\Controller\LogoutController::logout
    methods: GET|POST

app_dashboard:
    path: /dashboard
    controller: App\Controller\MainController::dashboard

app_subscription_new:
    path: /dashboard/subscription/new
    controller: App\Controller\SubscriptionController::new
    methods: GET|POST

app_subscription_edit:
    path: /dashboard/subscription/edit/{id}
    controller: App\Controller\SubscriptionController::edit
    methods: GET|POST

app_subscription_index:
    path: /dashboard/subscription
    controller: App\Controller\SubscriptionController::index
    methods: GET

app_subscription_delete:
    path: /dashboard/subscription/{id}
    controller: App\Controller\SubscriptionController::delete
    methods: DELETE

app_user_index:
    path: /dashboard/users
    controller: App\Controller\UserController::index
    methods: GET

app_user_delete:
    path: /dashboard/users/{id}
    controller: App\Controller\UserController::delete
    methods: DELETE

app_command_index:
    path: /dashboard/command
    controller: App\Controller\CommandController::index
    methods: GET

app_command_execute:
    path: /dashboard/command/{command}
    controller: App\Controller\CommandController::execute
    methods: POST

app_broadcast_index:
    path: /dashboard/broadcast
    controller: App\Controller\BroadcastController::index
    methods: GET|POST

app_promotion_index:
    path: /dashboard/promotion
    controller: App\Controller\PromotionController::index
    methods: GET

app_promotion_edit:
    path: /dashboard/promotion/edit/{id}
    controller: App\Controller\PromotionController:edit
    methods: GET|POST

app_promotion_new:
    path: /dashboard/promotion/new
    controller: App\Controller\PromotionController:new
    methods: GET|POST

app_promotion_delete:
    path: /dashboard/promotion/{id}
    controller: App\Controller\PromotionController:delete
    methods: DELETE
